2024-02-10 19:17:43.372444: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-10 19:17:43.726127: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-10 19:17:43.726232: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-10 19:17:43.737095: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-10 19:17:43.752305: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-10 19:17:48.313264: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Matplotlib created a temporary cache directory at /tmp/slurm/518565/matplotlib-_6931pdq because the default path (/home/nlin06/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/scratch/st-sielmann-1/agrobot/grape-ld/__main__.py", line 97, in <module>
    data = load_data()
  File "/scratch/st-sielmann-1/agrobot/grape-ld/__main__.py", line 28, in load_data
    train_ds, dev_ds = tf.keras.utils.image_dataset_from_directory(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/keras/src/utils/image_dataset.py", line 243, in image_dataset_from_directory
    raise ValueError(
ValueError: No training images found in directory data/concatenated_datasets. Allowed formats: ('.bmp', '.gif', '.jpeg', '.jpg', '.png')
