Retrying (Retry(total=239, connect=239, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada5253f0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=238, connect=238, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada5255a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=237, connect=237, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada525720>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=236, connect=236, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada5258a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=235, connect=235, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada525a20>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=234, connect=234, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada525ba0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=233, connect=233, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada525d20>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=232, connect=232, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada525ea0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=231, connect=231, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada526020>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=230, connect=230, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada5261a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=229, connect=229, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada526320>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=228, connect=228, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada5264a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=227, connect=227, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada4f32b0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=226, connect=226, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada524b80>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=225, connect=225, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada526650>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=224, connect=224, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada5267d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=223, connect=223, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada526950>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=222, connect=222, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada526ad0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=221, connect=221, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada526c50>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=220, connect=220, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada526dd0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=219, connect=219, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada526f50>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=218, connect=218, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada5270d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=217, connect=217, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada527250>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=216, connect=216, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada5273d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=215, connect=215, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada527550>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=214, connect=214, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada5276d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=213, connect=213, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada527850>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=212, connect=212, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada5279d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=211, connect=211, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada527b50>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=210, connect=210, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada527cd0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=209, connect=209, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada527e50>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=208, connect=208, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaada527fd0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=207, connect=207, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe0190>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=206, connect=206, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe0310>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=205, connect=205, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe0490>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=204, connect=204, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe0610>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=203, connect=203, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe0790>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=202, connect=202, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe0910>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=201, connect=201, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe0a90>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=200, connect=200, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe0c10>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=199, connect=199, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe0d90>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=198, connect=198, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe0f10>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=197, connect=197, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe1090>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=196, connect=196, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe1210>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=195, connect=195, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe1390>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=194, connect=194, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe1540>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=193, connect=193, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe16f0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=192, connect=192, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe18a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=191, connect=191, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe1a50>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=190, connect=190, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe1c00>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=189, connect=189, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe1db0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=188, connect=188, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe1f60>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=187, connect=187, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe2110>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=186, connect=186, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe22c0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=185, connect=185, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe2470>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=184, connect=184, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe2620>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=183, connect=183, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe27d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=182, connect=182, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe2980>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=181, connect=181, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe2b30>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=180, connect=180, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe2ce0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=179, connect=179, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe2e90>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=178, connect=178, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe3040>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=177, connect=177, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe31f0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=176, connect=176, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe33a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=175, connect=175, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe3550>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=174, connect=174, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe3700>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=173, connect=173, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe38b0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=172, connect=172, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe3a60>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=171, connect=171, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe3c10>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=170, connect=170, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe3dc0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=169, connect=169, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadabe3f70>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=168, connect=168, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac30160>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=167, connect=167, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac30310>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=166, connect=166, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac304c0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=165, connect=165, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac30670>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=164, connect=164, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac30820>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=163, connect=163, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac309d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=162, connect=162, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac30b80>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=161, connect=161, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac30d30>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=160, connect=160, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac30ee0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=159, connect=159, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac31090>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=158, connect=158, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac31240>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=157, connect=157, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac313f0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=156, connect=156, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac315a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=155, connect=155, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac31750>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=154, connect=154, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac31900>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=153, connect=153, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac31ab0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=152, connect=152, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac31c60>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=151, connect=151, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac31e10>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=150, connect=150, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac31fc0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=149, connect=149, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac32170>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=148, connect=148, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac32320>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=147, connect=147, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac324d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=146, connect=146, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac32680>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=145, connect=145, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac32830>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=144, connect=144, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac329e0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=143, connect=143, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac32b90>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=142, connect=142, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac32d40>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=141, connect=141, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac32ef0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=140, connect=140, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac330a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=139, connect=139, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac33250>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=138, connect=138, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac33400>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=137, connect=137, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac335b0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=136, connect=136, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac33760>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=135, connect=135, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac33910>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=134, connect=134, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac33ac0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=133, connect=133, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac33c70>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=132, connect=132, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac33e20>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=131, connect=131, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac33fd0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=130, connect=130, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac701c0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=129, connect=129, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac70370>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=128, connect=128, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac70520>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=127, connect=127, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac706d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=126, connect=126, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac70880>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=125, connect=125, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac70a60>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=124, connect=124, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac70c10>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=123, connect=123, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac70dc0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=122, connect=122, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac70f70>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=121, connect=121, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac71120>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=120, connect=120, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac712d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=119, connect=119, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac71480>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=118, connect=118, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac71630>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=117, connect=117, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac717e0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=116, connect=116, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac71990>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=115, connect=115, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac71b40>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=114, connect=114, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac71cf0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=113, connect=113, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac71ea0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=112, connect=112, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac72050>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=111, connect=111, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac72200>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=110, connect=110, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac723b0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=109, connect=109, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac72560>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=108, connect=108, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac72710>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=107, connect=107, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac728c0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=106, connect=106, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac72a70>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=105, connect=105, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac72c20>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=104, connect=104, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac72dd0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=103, connect=103, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac72f80>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=102, connect=102, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac73130>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=101, connect=101, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac732e0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=100, connect=100, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac73490>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=99, connect=99, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac73640>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=98, connect=98, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac737f0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=97, connect=97, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac739a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=96, connect=96, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac73b50>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=95, connect=95, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac73d00>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=94, connect=94, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadac73eb0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=93, connect=93, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbc0a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=92, connect=92, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbc250>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=91, connect=91, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbc400>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=90, connect=90, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbc5b0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=89, connect=89, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbc760>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=88, connect=88, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbc910>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=87, connect=87, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbcac0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=86, connect=86, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbcc70>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=85, connect=85, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbce20>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=84, connect=84, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbcfd0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=83, connect=83, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbd180>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=82, connect=82, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbd330>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=81, connect=81, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbd4e0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=80, connect=80, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbd690>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=79, connect=79, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbd840>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=78, connect=78, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbd9f0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=77, connect=77, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbdba0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=76, connect=76, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbdd50>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=75, connect=75, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbdf00>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=74, connect=74, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbe0b0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=73, connect=73, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbe260>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=72, connect=72, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbe410>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=71, connect=71, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbe5c0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=70, connect=70, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbe770>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=69, connect=69, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbe920>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=68, connect=68, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbead0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=67, connect=67, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbec80>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=66, connect=66, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbee30>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=65, connect=65, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbefe0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=64, connect=64, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbf190>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=63, connect=63, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbf340>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=62, connect=62, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbf4f0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=61, connect=61, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbf6a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=60, connect=60, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbf850>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=59, connect=59, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbfa00>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=58, connect=58, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbfbb0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=57, connect=57, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbfd60>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=56, connect=56, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadacbff10>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=55, connect=55, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad08100>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=54, connect=54, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad082b0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=53, connect=53, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad08460>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=52, connect=52, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad08610>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=51, connect=51, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad087c0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=50, connect=50, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad08970>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=49, connect=49, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad08b20>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=48, connect=48, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad08cd0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=47, connect=47, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad08e80>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=46, connect=46, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad09030>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=45, connect=45, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad091e0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=44, connect=44, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad09390>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=43, connect=43, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad09540>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=42, connect=42, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad096f0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=41, connect=41, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad098a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=40, connect=40, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad09a50>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=39, connect=39, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad09c00>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=38, connect=38, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad09db0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=37, connect=37, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad09f60>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=36, connect=36, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0a110>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=35, connect=35, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0a2c0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=34, connect=34, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0a470>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=33, connect=33, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0a620>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=32, connect=32, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0a7d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=31, connect=31, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0a980>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=30, connect=30, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0ab30>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=29, connect=29, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0ace0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=28, connect=28, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0ae90>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=27, connect=27, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0b040>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=26, connect=26, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0b1f0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=25, connect=25, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0b3a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=24, connect=24, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0b550>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=23, connect=23, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0b700>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=22, connect=22, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0b8b0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=21, connect=21, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0ba60>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=20, connect=20, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0bc10>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=19, connect=19, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0bdc0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=18, connect=18, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad0bf70>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=17, connect=17, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad50160>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=16, connect=16, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad50310>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=15, connect=15, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad504c0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=14, connect=14, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad50670>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=13, connect=13, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad50820>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=12, connect=12, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad509d0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=11, connect=11, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad50b80>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=10, connect=10, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad50d30>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=9, connect=9, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad50ee0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=8, connect=8, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad51090>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=7, connect=7, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad51240>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=6, connect=6, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad513f0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=5, connect=5, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad515a0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=4, connect=4, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad51750>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=3, connect=3, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad51900>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=2, connect=2, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad51ab0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=1, connect=1, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad51c60>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Retrying (Retry(total=0, connect=0, read=240, redirect=240, status=240)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad51e10>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')': /auth.login
Traceback (most recent call last):
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x2aaadad51fc0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  [Previous line repeated 237 more times]
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.clear.ml', port=443): Max retries exceeded with url: /auth.login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad51fc0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_api/session/session.py", line 834, in _do_refresh_token
    res = self._send_request(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_api/session/session.py", line 411, in _send_request
    res = self.__http_session.request(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_api/utils.py", line 98, in send
    return super(SessionWithTimeout, self).send(request, **kwargs)
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.clear.ml', port=443): Max retries exceeded with url: /auth.login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad51fc0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/st-sielmann-1/agrobot/grape-ld/__main__.py", line 2, in <module>
    task = Task.init(project_name='Test Project', task_name='Init')
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/task.py", line 594, in init
    task = cls._create_dev_task(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/task.py", line 3790, in _create_dev_task
    task = cls(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/task.py", line 209, in __init__
    super(Task, self).__init__(**kwargs)
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_interface/task/task.py", line 161, in __init__
    super(Task, self).__init__(id=task_id, session=session, log=log)
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_interface/base.py", line 149, in __init__
    super(IdObjectBase, self).__init__(session, log, **kwargs)
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_interface/base.py", line 41, in __init__
    self._session = session or self._get_default_session()
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_interface/base.py", line 119, in _get_default_session
    InterfaceBase._default_session = Session(
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_api/session/session.py", line 160, in __init__
    self._connect()
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_api/session/session.py", line 227, in _connect
    self.refresh_token()
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_api/session/token_manager.py", line 112, in refresh_token
    self._set_token(self._do_refresh_token(self.__token, exp=self.req_token_expiration_sec))
  File "/home/nlin06/miniconda3/envs/grape-ld/lib/python3.10/site-packages/clearml/backend_api/session/session.py", line 873, in _do_refresh_token
    raise LoginError('Unrecognized Authentication Error: {} {}'.format(type(ex), ex))
clearml.backend_api.session.session.LoginError: Unrecognized Authentication Error: <class 'requests.exceptions.ConnectTimeout'> HTTPSConnectionPool(host='api.clear.ml', port=443): Max retries exceeded with url: /auth.login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x2aaadad51fc0>, 'Connection to api.clear.ml timed out. (connect timeout=3.0)'))
